#服务端口
server:
  port: 7001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:

  application:
    name: trade-service

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shtrade-tradeservice
    username: root
    password:
    # druid 连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  data:
    elasticsearch:
      cluster-name: elasticsearch-application
      cluster-nodes: 127.0.0.1:9300
      path:
        logs: ../elasticsearch/log #elasticsearch日志存储目录
        data: ../elasticsearch/data #elasticsearch数据存储目录


mybatis:
  mapper-locations: classpath:mapping/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: true

feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000
